# Copyright 2017 AT&T Intellectual Property.  All other rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for divingbell.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

images:
  divingbell: 'ubuntu:16.04'
  pull_policy: IfNotPresent

conf:
  chroot_mnt_path: '/mnt'
  log_colors: False

pod:
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        ethtool:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 100%
        mounts:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 100%
        uamlite:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 100%
        sysctl:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 100%
